### ISSUE TITLE
[Bug] @Builder & @Column 관련 JPA 테이블 생성 버그

### ISSUE THREAD

**Issue by m-dzn** [dnd-side-project/dnd-7th-2-backend#36]
# 버그 내용

## 버그 상황 설명

> 3줄 요약

develop 브랜치에서 Application을 Run하면
`Applicant`, `Comment`, `LectureRecruiting`, `Recruiting` Entity에서
`@Builder` 및 `@Column` 어노테이션 관련 컴파일 에러가 발생합니다.

## 재현 방법

1. d74f2385 머지 커밋 이후 develop 브랜치를 IDE에서 run하면 다음과 같은 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/63327304/183293214-de702adf-2b04-47cd-8929-a19db1ada5c4.png)

**Comment by Cho-D-YoungRae** [comment]
`Applicant` 에 `@Builder` 가 없이 `@Builder.Default를 사용한 것 같습니다.

**Comment by m-dzn** [comment]
그거랑 @JoinColumn 발견해서 수정하니 잘 되네요ㅎㅎ
확인 받고 머지하려고 PR로 올렸으니 보고 머지해주세요
